"""Create a compact, reproducible excerpt from a complete radar-pose-demo source tree.

The checked-in release contains the generated excerpt, so CI needs no access to the
full private research workspace. This command is only needed to choose/regenerate
the excerpt from the original, complete demo directory.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "web"
POSE_DATA = "method_comparison_jan15_cfear_lite_pose_data.js"
EXPECTED_SEQUENCE = "2019-01-15-13-06-37"
FIELDS = 32


def load_pose_data(path: Path) -> dict[str, Any]:
    script = path.read_text(encoding="utf-8").strip()
    prefix = "window.RADAR_POSE_METHOD_DATA="
    if not script.startswith(prefix):
        raise ValueError(f"Unexpected pose data format: {path}")
    data = json.loads(script[len(prefix) :].rstrip(";"))
    if not isinstance(data.get("frames"), list) or not isinstance(data.get("metadata"), dict):
        raise ValueError("Pose data is missing metadata or frames")
    return data


def require_replace(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise ValueError(f"Expected one {label} source fragment, found {count}")
    return text.replace(old, new, 1)


def clean_generated_assets() -> None:
    """Remove only files generated by this script, after checking their exact roots."""
    web_root = WEB.resolve()
    if web_root != ROOT.resolve() / "web":
        raise RuntimeError("Refusing to clean an unexpected web output path")
    for directory in (WEB / "assets" / "radar", WEB / "assets" / "stereo"):
        if directory.exists():
            if directory.resolve().parent != (WEB / "assets").resolve():
                raise RuntimeError(f"Unexpected generated asset directory: {directory}")
            for path in directory.iterdir():
                if not path.is_file() or not re.fullmatch(r"\d+\.jpg", path.name):
                    raise RuntimeError(f"Unexpected file in generated asset directory: {path}")
                path.unlink()
    for directory in (WEB / "assets" / "radar", WEB / "assets" / "stereo"):
        if directory.exists() and not any(directory.iterdir()):
            directory.rmdir()
    data_dir = WEB / "data"
    if data_dir.exists():
        if data_dir.resolve().parent != WEB.resolve():
            raise RuntimeError(f"Unexpected data directory: {data_dir}")
        for path in data_dir.iterdir():
            if not path.is_file() or path.name != "pose-excerpt.js":
                raise RuntimeError(f"Unexpected file in generated data directory: {path}")
            path.unlink()


def write_html(source_html: Path, metadata: dict[str, Any]) -> str:
    html = source_html.read_text(encoding="utf-8")
    replacements = (
        ("<title>Radar Localization</title>", "<title>Radar Pose Playback · Oxford recorded sequence</title>", "title"),
        (
            '<p class="eyebrow">RADAR LOCALIZATION</p>',
            '<p class="eyebrow">RADAR LOCALIZATION · RECORDED SEQUENCE</p>',
            "eyebrow",
        ),
        (
            "<h1>Where is the car, and which way is it facing?</h1>",
            "<h1>Radar pose sequence replay <span lang=\"zh-CN\">真实序列回放</span></h1>",
            "heading",
        ),
        (
            '<p class="subtitle">Radar input. Six global pose estimates.</p>',
            '<p class="subtitle">Oxford Radar RobotCar · sequence 2019-01-15-13-06-37 · '
            "saved sensor frames and precomputed pose estimates; no live inference in this browser.</p>",
            "subtitle",
        ),
        (
            '<main class="flow" aria-label="Radar localization animation">',
            '<main class="flow" aria-label="Recorded radar and stereo frame replay">',
            "main content label",
        ),
        (
            '<section class="model-flow" aria-label="Radar pose model">',
            '<section class="model-flow" aria-label="Recorded frame playback diagram; no model runs here">',
            "model diagram label",
        ),
        (
            '<p>Radar-primary fusion</p>',
            '<p>Precomputed estimate · CFEAR-lite + model</p>',
            "radar method label",
        ),
        ("<h3>CFEAR-lite + Model</h3>", "<h3>Radar-primary estimate</h3>", "radar estimate heading"),
        ("<h3>Temporal Model</h3>", "<h3>Temporal estimate</h3>", "temporal estimate heading"),
        ("<h3>Single Frame Model</h3>", "<h3>Single-frame estimate</h3>", "single-frame estimate heading"),
        ("<h3>VO + Model</h3>", "<h3>VO-primary estimate</h3>", "VO estimate heading"),
        (
            '<span id="vo-primary-state" class="state-badge vo-primary-badge">VO</span>',
            '<span id="vo-primary-state" class="state-badge vo-primary-badge" aria-label="Stored method selection for this frame" title="Recorded method selection stored per frame; no live inference">SAVED VO</span>',
            "stored method badge",
        ),
        (
            '<p>V113</p>',
            '<p>Precomputed estimate · V113</p>',
            "temporal method label",
        ),
        (
            '<p>V86 · no temporal constraint</p>',
            '<p>Precomputed estimate · V86 · no temporal constraint</p>',
            "single-frame method label",
        ),
        (
            '<p>V118 · tuned VO-primary</p>',
            '<p>Precomputed estimate · V118 tuned VO-primary</p>',
            "VO method label",
        ),
    )
    for old, new, label in replacements:
        html = require_replace(html, old, new, label)
    html, diagram_labels = re.subn(
        r"<span>AI</span>\s*<small>Radar Pose<br\s*/>Model</small>",
        "<span>DATA</span>\n            <small>Saved pose<br />estimates</small>",
        html,
    )
    if diagram_labels != 1:
        raise ValueError(f"Expected one original model diagram label, found {diagram_labels}")

    start = metadata["excerptStartFrame"]
    end = metadata["excerptEndFrame"]
    duration = metadata["recordedDurationSeconds"]
    interval = metadata["playbackIntervalMs"]
    footer = f'''      <footer class="replay-footer">
        <p class="legend-line">Recorded frames {start}–{end} · {duration:.2f} seconds of capture · replay speed {metadata["replaySpeed"]:.1f}×</p>
        <p class="replay-note">All poses shown below are saved per-frame estimates. 不在浏览器中运行模型推理。 The browser only replays these records; it does not run a model or perform live inference.</p>
        <p class="legend-line">NED world frame · Space pauses · R restarts · playback interval {interval} ms per saved frame</p>
        <p id="status" class="status">Loading saved pose records…</p>
        <p class="attribution">Data: <a href="https://oxford-robotics-institute.github.io/radar-robotcar-dataset/" rel="noreferrer">Oxford Radar RobotCar</a> + <a href="https://robotcar-dataset.robots.ox.ac.uk/" rel="noreferrer">Oxford RobotCar</a> ·
          <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" rel="license noreferrer">CC BY-NC-SA 4.0</a> ·
          <a href="data-license.html">attribution, license and citations</a></p>
      </footer>'''
    footer_start = html.find("      <footer>")
    footer_end = html.find("      </footer>", footer_start)
    if footer_start < 0 or footer_end < 0:
        raise ValueError("The original demo footer was not found")
    footer_end += len("      </footer>")
    html = html[:footer_start] + footer + html[footer_end:]
    return html


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, type=Path, help="Complete radar-pose-demo directory")
    parser.add_argument("--start", type=int, default=0, help="First original sequence frame index")
    parser.add_argument("--frames", type=int, default=240, help="Number of contiguous saved frames")
    parser.add_argument("--playback-interval-ms", type=int, default=100)
    args = parser.parse_args()

    source = args.source.resolve()
    if args.start < 0 or args.frames < 2 or args.playback_interval_ms <= 0:
        raise ValueError("start must be nonnegative; at least two frames and a positive playback interval are required")
    data = load_pose_data(source / "data" / POSE_DATA)
    source_frames = data["frames"]
    source_metadata = data["metadata"]
    if source_metadata.get("sequence") != EXPECTED_SEQUENCE:
        raise ValueError(f"Unexpected sequence: {source_metadata.get('sequence')!r}")
    if int(source_metadata.get("sampleCount", -1)) != len(source_frames):
        raise ValueError("Source metadata sampleCount does not match the pose rows")
    rows = source_frames[args.start : args.start + args.frames]
    if len(rows) != args.frames:
        raise ValueError("Requested excerpt is outside the recorded sequence")
    for offset, row in enumerate(rows):
        if not isinstance(row, list) or len(row) != FIELDS:
            raise ValueError(f"Unexpected row schema at excerpt offset {offset}")
        if int(row[0]) != args.start + offset:
            raise ValueError(f"Excerpt is not contiguous at source frame {args.start + offset}")

    radar_names = [f"{int(row[1])}.jpg" for row in rows]
    stereo_names = [f"{int(row[31])}.jpg" for row in rows]
    if len(set(radar_names)) != len(rows) or len(set(stereo_names)) != len(rows):
        raise ValueError("Sensor timestamps must be unique within the excerpt")
    for kind, names in (("radar", radar_names), ("stereo", stereo_names)):
        for name in names:
            path = source / "assets" / kind / name
            if not path.is_file():
                raise FileNotFoundError(path)

    clean_generated_assets()
    for kind, names in (("radar", radar_names), ("stereo", stereo_names)):
        target = WEB / "assets" / kind
        target.mkdir(parents=True, exist_ok=True)
        for name in names:
            shutil.copyfile(source / "assets" / kind / name, target / name)

    metadata = dict(source_metadata)
    for key in ("metrics", "stereoSource", "radarPrimarySource", "voPrimarySource"):
        metadata.pop(key, None)
    first_timestamp = int(rows[0][1])
    last_timestamp = int(rows[-1][1])
    recorded_duration = (last_timestamp - first_timestamp) / 1_000_000
    replay_duration = (args.frames - 1) * args.playback_interval_ms / 1000
    metadata.update(
        {
            "sampleCount": len(rows),
            "sourceSampleCount": len(source_frames),
            "excerptStartFrame": int(rows[0][0]),
            "excerptEndFrame": int(rows[-1][0]),
            "firstRadarTimestamp": first_timestamp,
            "lastRadarTimestamp": last_timestamp,
            "recordedDurationSeconds": round(recorded_duration, 6),
            "playbackIntervalMs": args.playback_interval_ms,
            "replaySpeed": round(recorded_duration / replay_duration, 3),
            "recordingMode": "saved-per-frame-estimates",
            "liveInference": False,
            "dataLicense": "CC BY-NC-SA 4.0",
            "sourceAttribution": "Oxford Radar RobotCar and Oxford RobotCar datasets",
        }
    )
    excerpt = {"metadata": metadata, "frames": rows}
    WEB.mkdir(parents=True, exist_ok=True)
    license_template = (ROOT / "templates" / "data-license.html").read_text(encoding="utf-8")
    license_page = license_template
    for token, value in (
        ("__FRAME_COUNT__", str(len(rows))),
            ("__FRAME_START__", str(metadata["excerptStartFrame"])),
        ("__FRAME_END__", str(metadata["excerptEndFrame"])),
        ("__SEQUENCE__", EXPECTED_SEQUENCE),
        ("__DURATION__", f"{recorded_duration:.2f}"),
    ):
        if license_page.count(token) != 1:
            raise ValueError(f"Expected one {token} license template marker")
        license_page = license_page.replace(token, value, 1)
    (WEB / "data-license.html").write_text(license_page, encoding="utf-8", newline="\n")
    data_dir = WEB / "data"
    data_dir.mkdir(exist_ok=True)
    compact_json = json.dumps(excerpt, ensure_ascii=False, separators=(",", ":"))
    (data_dir / "pose-excerpt.js").write_text(
        "window.RADAR_POSE_METHOD_DATA=" + compact_json + ";\n", encoding="utf-8"
    )

    source_html = source / "indexbak.html"
    html = write_html(source_html, metadata)
    for name in ("index.html", "indexbak.html", "index-global.html"):
        (WEB / name).write_text(html, encoding="utf-8", newline="\n")
    shutil.copyfile(source / "app.js", WEB / "app.js")
    app_path = WEB / "app.js"
    app = app_path.read_text(encoding="utf-8")
    app = require_replace(
        app,
        'status.textContent = paused ? "Paused" : `Playing ${index + 1} / ${clip.length}`;',
        'status.textContent = paused ? "Paused · saved pose replay" : `Recorded pose replay ${index + 1} / ${clip.length} · no live inference`;',
        "playback status",
    )
    app = require_replace(
        app,
        'status.textContent = `Loading sensor frames ${loaded} / ${initial.length}`;',
        'status.textContent = `Loading saved radar/stereo frames ${loaded} / ${initial.length}`;',
        "preload status",
    )
    app = require_replace(
        app,
        'voBadge.textContent = modelAccepted ? "MODEL" : "VO";',
        'voBadge.textContent = modelAccepted ? "SAVED MODEL" : "SAVED VO";',
        "stored method badge text",
    )
    app_path.write_text(app, encoding="utf-8", newline="\n")
    shutil.copyfile(source / "styles.css", WEB / "styles.css")
    css_path = WEB / "styles.css"
    css = css_path.read_text(encoding="utf-8")
    css += '''\n\n/* Static replay controls and attribution for this recorded-data module. */
.signal::after { display: none; animation: none; }
.replay-footer { display: grid; gap: 0.35rem; padding: 0.8rem 1rem; background: rgba(12, 20, 28, 0.88); border: 1px solid rgba(81, 216, 238, 0.16); border-radius: 0.7rem; font-size: clamp(0.56rem, 0.7vw, 0.78rem); }
.replay-footer p { margin: 0; }
.replay-note { color: #e9f1ef; }
.attribution { color: #b8c7cd; }
.attribution a { color: #7fe5f3; text-decoration: underline; text-underline-offset: 0.16em; }
.attribution a:focus-visible { outline: 2px solid #7fe5f3; outline-offset: 2px; }
@media (max-width: 760px) { .replay-footer { font-size: 0.72rem; } }
'''
    css_path.write_text(css, encoding="utf-8", newline="\n")
    (WEB / "config.js").write_text(
        "window.DEMO_CONFIG = {\n"
        '  radarImageDirectory: "./assets/radar/",\n'
        '  stereoImageDirectory: "./assets/stereo/",\n'
        '  poseDataScript: "./data/pose-excerpt.js",\n'
        '  startFrame: 0,\n'
        f'  frameCount: {len(rows)},\n'
        f'  intervalMs: {args.playback_interval_ms},\n'
        "  mapSpanMetres: 128,\n"
        "};\n",
        encoding="utf-8",
        newline="\n",
    )
    print(
        f"Prepared sequence {EXPECTED_SEQUENCE}, original frames "
        f"{metadata['excerptStartFrame']}–{metadata['excerptEndFrame']} "
        f"({len(rows)} contiguous samples; {recorded_duration:.3f}s capture; "
        f"{len(radar_names)} radar + {len(stereo_names)} stereo images)"
    )


if __name__ == "__main__":
    main()
